cmake_minimum_required(VERSION 4.1)
project(mvm00075_PAG)

set(CMAKE_CXX_STANDARD 20)

# Define variables agrupando nombres de archivo
file( GLOB MY_FILES *.cpp ) # Código fuente de tu proyecto
file( GLOB GLAD_FILES GLAD/src/*.c ) # Código fuente de GLAD
file( GLOB IMGUI_FILES imgui/src/*.cpp ) # Código fuente de ImGUI

# Indica qué archivos hay que compilar para generar el ejecutable
add_executable( ${PROJECT_NAME} ${MY_FILES}
                ${GLAD_FILES}
                ${IMGUI_FILES}

)

# Indica directorios (adicionales a los por defecto) para buscar includes
target_include_directories( ${PROJECT_NAME} PUBLIC GLAD/include imgui/include)

target_link_libraries( ${PROJECT_NAME} GL glfw )